export const TRV_MAX_COUNT = 3;
export const PERSISTENCE_VERSION = 1;
export const APPLIED_POWER_MAX_AGE_MINUTES = 30;

export const CATCHUP_TIME_SECONDS = 7200;
export const DEFAULT_THERMAL_CAPACITY_PER_M3 = 40000;
export const DISTRIBUTION_ALPHA = 0.5;
export const MAX_CATCHUP_POWER_RATIO = 0.6;
export const MAX_FLOW_FACTOR = 1.5;
export const MAX_ROOM_ERROR = 3;
export const MIN_FLOW_FACTOR = 0;
export const RADIATOR_EXPONENT = 1.3;

export const CAPACITY_LEARNING_RATE = 0.002;
export const MAX_PREDICTION_ERROR_C = 3;
export const MAX_UA_LEARNING_HEATING_POWER_W = 200;
export const MIN_CAPACITY_LEARNING_HEATING_POWER_W = 150;
export const MIN_DELTA_C_FOR_LEARNING = 0.05;
export const MIN_LEARNING_INTERVAL_SECONDS = 300;
export const PERSISTENCE_THRESHOLD = 0.002;
export const UA_LEARNING_RATE = 0.005;

export const SENSOR_OUTLIER_MIN_SAMPLES = 3;
export const SENSOR_OUTLIER_MAX_DELTA_C = 5;
export const SENSOR_OUTLIER_WINDOW_SIZE = 10;
export const SENSOR_OUTLIER_DRIFT_REPEAT_COUNT = 3;
export const SENSOR_OUTLIER_DRIFT_MATCH_DELTA_C = 1;
export const SENSOR_OUTLIER_DRIFT_MAX_INTERVAL_M = 5;
